query GET_COMMENT_CHILD($commentId: Int, $pageSize: Int, $targetPage: Int) {
  commentBy(commentId: $commentId) {
    commentId
    childDetail(commentId: $commentId, pageSize: $pageSize, targetPage: $targetPage) {
      childAmount
      pageCount
      pageSize
      targetPage
      detailList
    }
  }
}
